// Command benchvault builds a vault for measuring Atlas Notes against.
//
// The vault is a function of its seed and size and nothing else, so the same
// command builds the same notes, byte for byte, on any machine and any day.
// That is the whole point of it. The performance figures in the changelog were
// once measured against a vault that was generated by hand and then lost, and
// from then on nobody, including the person who wrote them, could check them.
//
//	go run ./cmd/benchvault -out /tmp/atlas-bench -n 10000
//
// It writes through the storage package, so the files are in exactly the
// format the app reads, and it confines itself to -out: the data and config
// directories are both pointed there before anything is opened, so it cannot
// touch a real vault by accident. scripts/bench.sh is what normally runs it.
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"atlas-notes/internal/storage"
)

func main() {
	out := flag.String("out", "", "directory to build the vault in (must be empty or absent)")
	n := flag.Int("n", 10000, "number of notes")
	seed := flag.Int64("seed", 20260927, "the same seed builds the same vault")
	flag.Parse()

	if *out == "" {
		fail("-out is required")
	}
	abs, err := filepath.Abs(*out)
	if err != nil {
		fail(err.Error())
	}
	if entries, err := os.ReadDir(abs); err == nil && len(entries) > 0 {
		fail(abs + " is not empty; benchvault only builds into an empty directory")
	}
	// Both locations are pinned inside -out before storage is touched, so
	// nothing here can resolve to the real ~/.local/share or ~/.config.
	os.Setenv("ATLAS_DATA_HOME", abs)
	os.Setenv("ATLAS_CONFIG_HOME", filepath.Join(abs, "cfg"))

	g := newGen(*seed)
	s, err := storage.Open("", "")
	if err != nil {
		fail(err.Error())
	}

	folders := g.folders(40)
	start := time.Now()
	for i := 0; i < *n; i++ {
		folder := folders[g.r.Intn(len(folders))]
		name := fmt.Sprintf("%s %05d", g.title(), i)
		rel := name
		if folder != "" {
			rel = folder + "/" + name
		}
		if err := s.WriteNote(rel, g.note(name)); err != nil {
			fail(err.Error())
		}
	}
	if err := s.Close(); err != nil {
		fail(err.Error())
	}

	// Modification times, spread over most of a year so "recent" means
	// something. Walked in sorted order, so they land the same way every time.
	var files []string
	filepath.WalkDir(storage.DefaultVaultPath(), func(p string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() {
			files = append(files, p)
		}
		return nil
	})
	sort.Strings(files)
	base := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	var bytes int64
	for i, p := range files {
		t := base.Add(time.Duration(i*37%(260*24)) * time.Hour)
		os.Chtimes(p, t, t)
		if fi, err := os.Stat(p); err == nil {
			bytes += fi.Size()
		}
	}

	// A config that gives every run the same window, so layout costs compare.
	// Three panels fit at this width, and the update check is off, because a
	// benchmark that talks to the network measures the network.
	cfg := storage.DefaultConfig()
	cfg.VaultPath = ""
	cfg.WindowWidth, cfg.WindowHeight = 1400, 900
	cfg.LeftPanelWidth, cfg.RightPanelWidth = 280, 320
	cfg.CheckUpdates = false
	if err := storage.SaveConfig(cfg); err != nil {
		fail(err.Error())
	}

	fmt.Printf("benchvault: %d notes, %.1f MB on disk, seed %d, %s, in %s\n",
		len(files), float64(bytes)/(1<<20), *seed, time.Since(start).Round(time.Millisecond), abs)
}

// gen makes the text. Words are drawn from a vocabulary with a Zipf
// distribution, as words are in real writing: a few very common, a long tail
// seen once or twice. A vocabulary of a hundred words, which this started as,
// makes a search index look far smaller and far faster than real notes do.
type gen struct {
	r     *rand.Rand
	vocab []string
	zipf  *rand.Zipf
}

func newGen(seed int64) *gen {
	r := rand.New(rand.NewSource(seed))
	onsets := strings.Fields("b c d f g h j k l m n p r s t v w z br ch cl cr dr fl gr pl pr sh st str th tr")
	nuclei := strings.Fields("a e i o u ai ea ee io oo ou é")
	codas := []string{"", "", "n", "r", "s", "t", "l", "m", "nd", "st", "rk", "ng", "ck"}
	seen := map[string]bool{}
	var vocab []string
	for len(vocab) < 6000 {
		var b strings.Builder
		for s := 0; s < 1+r.Intn(3); s++ {
			b.WriteString(onsets[r.Intn(len(onsets))])
			b.WriteString(nuclei[r.Intn(len(nuclei))])
		}
		b.WriteString(codas[r.Intn(len(codas))])
		if w := b.String(); !seen[w] {
			seen[w] = true
			vocab = append(vocab, w)
		}
	}
	return &gen{r: r, vocab: vocab, zipf: rand.NewZipf(r, 1.07, 2, uint64(len(vocab)-1))}
}

func (g *gen) word() string { return g.vocab[g.zipf.Uint64()] }

func (g *gen) words(n int) string {
	w := make([]string, n)
	for i := range w {
		w[i] = g.word()
	}
	return strings.Join(w, " ")
}

func (g *gen) sentence() string {
	s := g.words(5 + g.r.Intn(16))
	return strings.ToUpper(s[:1]) + s[1:] + "."
}

func (g *gen) title() string {
	s := g.words(1 + g.r.Intn(3))
	return strings.ToUpper(s[:1]) + s[1:]
}

func (g *gen) folders(n int) []string {
	out := []string{""} // the vault root holds notes too
	for i := 0; i < n; i++ {
		f := g.title()
		if i%5 == 4 {
			f = out[1+g.r.Intn(len(out)-1)] + "/" + f
		}
		out = append(out, f)
	}
	return out
}

func (g *gen) note(title string) string {
	var b strings.Builder
	b.WriteString("# " + title + "\n\n")
	switch k := g.r.Intn(100); {
	case k < 30: // a checklist, some of it done, some of it prioritised
		prio := []string{"", "", "", "low", "medium", "high"}
		for i := 0; i < 3+g.r.Intn(20); i++ {
			mark := " "
			if g.r.Intn(3) == 0 {
				mark = "x"
			}
			fmt.Fprintf(&b, "- [%s] %s", mark, strings.TrimSuffix(g.sentence(), "."))
			if p := prio[g.r.Intn(len(prio))]; p != "" {
				fmt.Fprintf(&b, " <!-- priority:%s -->", p)
			}
			b.WriteByte('\n')
		}
	case k < 98: // ordinary prose
		g.prose(&b, 1+g.r.Intn(8))
	default: // the occasional very long note, like a prompt library
		g.prose(&b, 120+g.r.Intn(200))
	}
	return b.String()
}

func (g *gen) prose(b *strings.Builder, paras int) {
	for p := 0; p < paras; p++ {
		if g.r.Intn(4) == 0 {
			b.WriteString("## " + g.title() + "\n\n")
		}
		for s := 0; s < 2+g.r.Intn(5); s++ {
			b.WriteString(g.sentence() + " ")
		}
		b.WriteString("\n\n")
		if g.r.Intn(8) == 0 {
			b.WriteString("```\n" + g.words(8) + "\n```\n\n")
		}
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "benchvault:", msg)
	os.Exit(1)
}
