#!/usr/bin/env bash
# Turn Material Symbols downloads into the symbolic icons Atlas Notes embeds.
#
# Google's exports are already close to what GTK wants — a single filled path,
# no strokes — but they need three things doing to them:
#
#   * Renaming. Icon lookup goes current theme -> parents -> hicolor last, and
#     an icon called "search-symbolic" would lose to the system theme's own and
#     never appear. Everything is prefixed "atlas-" so it cannot collide. The
#     "-symbolic" suffix is what tells GTK the icon may be recoloured.
#   * A black fill. The exports carry whatever colour the website previewed
#     with, usually a pale grey. GTK overrides it when recolouring, but anything
#     else that renders the file — a thumbnailer, a browser — would show pale
#     grey on white.
#   * A nominal 16px size, which is what these are drawn at in the toolbar. The
#     viewBox is left alone; it defines the coordinate system, not the size.
#
# Run from the repository root:  scripts/import-icons.sh
#
# Sources are read from assets/icons-src/<material name>.svg and left in place;
# the results are written to internal/app/icons/, which main.go embeds.
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")/.."
src_dir=assets/icons-src
out_dir=internal/app/icons

# <Material Symbols name>:<installed name, without the atlas-/-symbolic wrapper>
map=(
    # Formatting toolbar
    format_bold:bold
    format_italic:italic
    format_strikethrough:strikethrough
    code:code
    format_h1:heading1
    format_h2:heading2
    format_paragraph:paragraph
    format_list_bulleted:bullet-list
    check_box:task
    format_quote:quote
    horizontal_rule:divider

    # Window and navigation
    menu:menu
    home:home
    left_panel_open:panel-left
    right_panel_open:panel-right
    search:search
    info:info

    # Vault panel
    folder:folder
    description:note
    checklist:checklist
    note_add:note-new
    add:add
    edit:edit
    delete:trash
    sort:sort
    history:recent

    # Locking and favourites
    lock:lock
    lock_open:lock-open
    star:star

    # Assistant
    chat:assistant
    bolt:prompts
    arrow_upward:send
    content_copy:copy
)

fail=0
mkdir -p "$out_dir"
for pair in "${map[@]}"; do
    src="$src_dir/${pair%%:*}.svg"
    dst="$out_dir/atlas-${pair##*:}-symbolic.svg"

    if [ ! -f "$src" ]; then
        echo "  missing: $src"
        fail=1
        continue
    fi

    # A stroke would not recolour: GTK forces the fill on rect, circle and path,
    # so stroked artwork keeps its own colour and turns invisible in dark mode.
    # Refuse rather than ship something that looks fine until the theme changes.
    if grep -q 'stroke' "$src"; then
        echo "  REFUSED: $src contains a stroke — convert it to outlines first"
        fail=1
        continue
    fi
    # A fill="none" bounding box becomes a solid square once GTK forces the fill.
    if grep -q 'fill="none"' "$src"; then
        echo "  REFUSED: $src has a fill=\"none\" element — remove it first"
        fail=1
        continue
    fi

    python3 - "$src" "$dst" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
svg = open(src).read().strip()
svg = re.sub(r'\s(width|height)="[^"]*"', '', svg, count=2)
svg = re.sub(r'\sfill="[^"]*"', '', svg, count=1)
svg = svg.replace('<svg ', '<svg width="16" height="16" fill="#000000" ', 1)
header = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- Material Symbols (Outlined, weight 400, grade 0, optical size 20),\n'
    '     Apache License 2.0 — see NOTICE. Filled paths only: GTK recolours a\n'
    '     symbolic icon by forcing the fill, so a stroke would not follow the\n'
    '     theme. Generated by scripts/import-icons.sh; edit the source file in\n'
    '     assets/icons-src rather than this. -->\n'
)
open(dst, 'w').write(header + svg + '\n')
PY
    echo "  $(basename "$src")  ->  $(basename "$dst")"
done

exit $fail
